DiSMEC++: dismec::prediction::ConfusionMatrixRecorder Class Reference
dismec::prediction::ConfusionMatrixRecorder Class Reference
#include <metrics.h>
Public Member Functions
ConfusionMatrixRecorder (long num_labels, long k)
void update (const pd_info_vec &prediction, const gt_info_vec &labels) override
void reduce (const MetricCollectionInterface &other) override
std::unique_ptr< MetricCollectionInterface > clone () const override
long get_k () const
ConfusionMatrix get_confusion_matrix (label_id_t label) const
Public Member Functions inherited from dismec::prediction::MetricCollectionInterface
MetricCollectionInterface (long num_labels)
virtual ~MetricCollectionInterface ()=default
long num_labels () const
Gets the number of labels.
Private Attributes
long m_K
long m_InstanceCount = 0
std::vector< ConfusionMatrix > m_Confusion
Additional Inherited Members
Public Types inherited from dismec::prediction::MetricCollectionInterface
using gt_info_vec = std::vector< sTrueLabelInfo >
using pd_info_vec = std::vector< sPredLabelInfo >
Detailed Description
Definition at line 47 of file metrics.h.
Constructor & Destructor Documentation
ConfusionMatrixRecorder()
ConfusionMatrixRecorder::ConfusionMatrixRecorder (long num_labels, long k)
Definition at line 25 of file metrics.cpp.
References m_Confusion, and dismec::prediction::MetricCollectionInterface::num_labels().
Member Function Documentation
clone()
std::unique_ptr< MetricCollectionInterface > ConfusionMatrixRecorder::clone () const override virtual
Implements dismec::prediction::MetricCollectionInterface.
Definition at line 65 of file metrics.cpp.
References m_K, and dismec::prediction::MetricCollectionInterface::num_labels().
get_confusion_matrix()
ConfusionMatrix ConfusionMatrixRecorder::get_confusion_matrix (label_id_t label) const
Definition at line 58 of file metrics.cpp.
References m_Confusion, m_InstanceCount, dismec::ssize(), and dismec::opaque_int_type< Tag, T >::to_index().
Referenced by dismec::prediction::MacroMetricReporter::get_values().
get_k()
long dismec::prediction::ConfusionMatrixRecorder::get_k () const inline
Definition at line 54 of file metrics.h.
References m_K.
Referenced by dismec::prediction::MacroMetricReporter::add_confusion_matrix(), dismec::prediction::MacroMetricReporter::add_coverage(), and dismec::prediction::MacroMetricReporter::add_reduction_helper().
reduce()
void ConfusionMatrixRecorder::reduce (const MetricCollectionInterface & other) override virtual
Implements dismec::prediction::MetricCollectionInterface.
Definition at line 46 of file metrics.cpp.
References ALWAYS_ASSERT_EQUAL, m_Confusion, m_InstanceCount, m_K, dismec::prediction::MetricCollectionInterface::num_labels(), and dismec::ssize().
update()
void ConfusionMatrixRecorder::update (const pd_info_vec & prediction, const gt_info_vec & labels) override virtual
Implements dismec::prediction::MetricCollectionInterface.
Definition at line 29 of file metrics.cpp.
References m_Confusion, m_InstanceCount, and m_K.
Member Data Documentation
m_Confusion
std::vector<ConfusionMatrix> dismec::prediction::ConfusionMatrixRecorder::m_Confusion private
Definition at line 59 of file metrics.h.
Referenced by ConfusionMatrixRecorder(), get_confusion_matrix(), reduce(), and update().
m_InstanceCount
long dismec::prediction::ConfusionMatrixRecorder::m_InstanceCount = 0 private
Definition at line 58 of file metrics.h.
Referenced by get_confusion_matrix(), reduce(), and update().
m_K
long dismec::prediction::ConfusionMatrixRecorder::m_K private
Definition at line 57 of file metrics.h.
Referenced by clone(), get_k(), reduce(), and update().
The documentation for this class was generated from the following files:
src/prediction/metrics.h
src/prediction/metrics.cpp