DiSMEC++: dismec::objective::LinearClassifierImpBase< Derived > Class Template Reference
dismec::objective::LinearClassifierImpBase< Derived > Class Template Reference
Implementation helper for linear classifier derived classes.
#include <linear.h>
Public Member Functions
LinearClassifierImpBase (std::shared_ptr< const GenericFeatureMatrix > X, std::unique_ptr< Objective > regularizer)
Public Member Functions inherited from dismec::objective::LinearClassifierBase
LinearClassifierBase (std::shared_ptr< const GenericFeatureMatrix > X)
long num_instances () const noexcept
long num_variables () const noexcept override
BinaryLabelVector & get_label_ref ()
void update_costs (real_t positive, real_t negative)
Public Member Functions inherited from dismec::objective::Objective
Objective ()
virtual ~Objective () noexcept=default
real_t value (const HashVector &location)
Evaluate the objective at the given location.
void diag_preconditioner (const HashVector &location, Eigen::Ref< DenseRealVector > target)
Get precondition to be used in CG optimization.
void project_to_line (const HashVector &location, const DenseRealVector &direction)
creates a function g such that g(a) = objective(location + a * direction) Use lookup_on_line() to evaluate g.
void gradient_at_zero (Eigen::Ref< DenseRealVector > target)
Gets the gradient for location zero.
void gradient (const HashVector &location, Eigen::Ref< DenseRealVector > target)
Evaluate the gradient at location.
void hessian_times_direction (const HashVector &location, const DenseRealVector &direction, Eigen::Ref< DenseRealVector > target)
Calculates the product of the Hessian matrix at location with direction.
void gradient_and_pre_conditioner (const HashVector &location, Eigen::Ref< DenseRealVector > gradient, Eigen::Ref< DenseRealVector > pre)
Combines the calculation of gradient and pre-conditioner, which may be more efficient in some cases.
Public Member Functions inherited from dismec::stats::Tracked
Tracked ()
Default constructor, creates the internal stats::StatisticsCollection.
void register_stat (const std::string &name, std::unique_ptr< Statistics > stat)
Registers a tracker for the statistics name.
std::shared_ptr< StatisticsCollection > get_stats () const
Gets an ownership-sharing reference to the StatisticsCollection.
Protected Member Functions
const Derived & derived () const
Derived & derived ()
real_t value_unchecked (const HashVector &location) override
real_t lookup_on_line (real_t position) override
Looks up the value of the objective on the line defined by the last call to project_to_line().
void project_to_line_unchecked (const HashVector &location, const DenseRealVector &direction) override
void gradient_unchecked (const HashVector &location, Eigen::Ref< DenseRealVector > target) override
void gradient_at_zero_unchecked (Eigen::Ref< DenseRealVector > target) override
void hessian_times_direction_unchecked (const HashVector &location, const DenseRealVector &direction, Eigen::Ref< DenseRealVector > target) override
void diag_preconditioner_unchecked (const HashVector &location, Eigen::Ref< DenseRealVector > target) override
void gradient_and_pre_conditioner_unchecked (const HashVector &location, Eigen::Ref< DenseRealVector > gradient, Eigen::Ref< DenseRealVector > pre) override
Protected Member Functions inherited from dismec::objective::LinearClassifierBase
const DenseRealVector & x_times_w (const HashVector &w)
Calculates the vector of feature matrix times weights w
template<class Derived >
void update_xtw_cache (const HashVector &new_weight, const Eigen::MatrixBase< Derived > &new_result)
Updates the cached value for x_times_w.
void project_linear_to_line (const HashVector &location, const DenseRealVector &direction)
Prepares the cache variables for line projection.
auto line_interpolation (real_t t) const
void declare_vector_on_last_line (const HashVector &location, real_t t) override
State that the given vector corresponds to a certain position on the line of the last line search.
const GenericFeatureMatrix & generic_features () const
const DenseFeatures & dense_features () const
const SparseFeatures & sparse_features () const
const DenseRealVector & costs () const
const BinaryLabelVector & labels () const
Protected Member Functions inherited from dismec::stats::Tracked
~Tracked ()
Non-virtual destructor. Declared protected, so we don't accidentally try to do a polymorphic delete.
template<class T >
void record (stat_id_t stat, T &&value)
Record statistics. This function just forwards all its arguments to the internal StatisticsCollection.
void declare_stat (stat_id_t index, StatisticMetaData meta)
Declares a new statistics. This function just forwards all its arguments to the internal StatisticsCollection.
void declare_tag (tag_id_t index, std::string name)
Declares a new tag. This function just forwards all its arguments to the internal StatisticsCollection.
template<class... Args>
void set_tag (tag_id_t tag, long value)
Set value of tag. This function just forwards all its arguments to the internal StatisticsCollection.
template<class... Args>
auto make_timer (stat_id_t id, Args... args)
Creates a new ScopeTimer using stats::record_scope_time.
Private Attributes
std::unique_ptr< Objective > m_Regularizer
Pointer to the regularizer.
Detailed Description
template<class Derived>
class dismec::objective::LinearClassifierImpBase< Derived >
Implementation helper for linear classifier derived classes.
Template Parameters
Derived The derived class, which is expected to provide the following functions:
template<typename Derived>
real_t value_from_xTw(const DenseRealVector& cost, const BinaryLabelVector& labels, const Eigen::DenseBase<Derived>& xTw);
void gradient_and_diag()
Definition at line 124 of file linear.h.
Constructor & Destructor Documentation
LinearClassifierImpBase()
template<class Derived > dismec::objective::LinearClassifierImpBase< Derived >::LinearClassifierImpBase (std::shared_ptr< const GenericFeatureMatrix > X, std::unique_ptr< Objective > regularizer) inline
Definition at line 126 of file linear.h.
Member Function Documentation
derived() [1/2]
template<class Derived > Derived& dismec::objective::LinearClassifierImpBase< Derived >::derived () inline protected
Definition at line 133 of file linear.h.
derived() [2/2]
template<class Derived > const Derived& dismec::objective::LinearClassifierImpBase< Derived >::derived () const inline protected
Definition at line 129 of file linear.h.
Referenced by dismec::objective::LinearClassifierImpBase< Derived >::diag_preconditioner_unchecked(), dismec::objective::LinearClassifierImpBase< Derived >::gradient_and_pre_conditioner_unchecked(), dismec::objective::LinearClassifierImpBase< Derived >::gradient_at_zero_unchecked(), dismec::objective::LinearClassifierImpBase< Derived >::gradient_unchecked(), dismec::objective::LinearClassifierImpBase< Derived >::hessian_times_direction_unchecked(), and dismec::objective::LinearClassifierImpBase< Derived >::value_unchecked().
diag_preconditioner_unchecked()
template<class Derived > void dismec::objective::LinearClassifierImpBase< Derived >::diag_preconditioner_unchecked (const HashVector & location, Eigen::Ref< DenseRealVector > target) inline override protected virtual
The function that does the actual computation. This is called in diag_preconditioner() after the arguments have been validated. The default implementation returns ones.
Reimplemented from dismec::objective::Objective.
Definition at line 170 of file linear.h.
References dismec::objective::LinearClassifierImpBase< Derived >::derived(), and dismec::objective::LinearClassifierImpBase< Derived >::m_Regularizer.
gradient_and_pre_conditioner_unchecked()
template<class Derived > void dismec::objective::LinearClassifierImpBase< Derived >::gradient_and_pre_conditioner_unchecked (const HashVector & location, Eigen::Ref< DenseRealVector > gradient, Eigen::Ref< DenseRealVector > pre) inline override protected virtual
The function that does the actual computation. This is called in gradient_and_pre_conditioner() after the arguments have been validated. The default implementation sucessively calls gradient() and diag_preconditioner().
Reimplemented from dismec::objective::Objective.
Definition at line 175 of file linear.h.
References dismec::objective::LinearClassifierImpBase< Derived >::derived(), dismec::objective::Objective::gradient(), and dismec::objective::LinearClassifierImpBase< Derived >::m_Regularizer.
gradient_at_zero_unchecked()
template<class Derived > void dismec::objective::LinearClassifierImpBase< Derived >::gradient_at_zero_unchecked (Eigen::Ref< DenseRealVector > target) inline override protected virtual
The function that does the actual computation. This is called in gradient_at_zero() after the argument has been validated. The default implementation is rather inefficient and creates a new temporary zero vector.
Reimplemented from dismec::objective::Objective.
Definition at line 158 of file linear.h.
References dismec::objective::LinearClassifierImpBase< Derived >::derived(), and dismec::objective::LinearClassifierImpBase< Derived >::m_Regularizer.
gradient_unchecked()
template<class Derived > void dismec::objective::LinearClassifierImpBase< Derived >::gradient_unchecked (const HashVector & location, Eigen::Ref< DenseRealVector > target) inline override protected virtual
The function that does the actual gradient computation. This is called in gradient() after the arguments have been validated.
Implements dismec::objective::Objective.
Definition at line 152 of file linear.h.
References dismec::objective::LinearClassifierImpBase< Derived >::derived(), and dismec::objective::LinearClassifierImpBase< Derived >::m_Regularizer.
hessian_times_direction_unchecked()
template<class Derived > void dismec::objective::LinearClassifierImpBase< Derived >::hessian_times_direction_unchecked (const HashVector & location, const DenseRealVector & direction, Eigen::Ref< DenseRealVector > target) inline override protected virtual
The function that does the actual computation. This is called in hessian_times_direction() after the arguments have been validated.
Implements dismec::objective::Objective.
Definition at line 163 of file linear.h.
References dismec::objective::LinearClassifierImpBase< Derived >::derived(), and dismec::objective::LinearClassifierImpBase< Derived >::m_Regularizer.
lookup_on_line()
template<class Derived > real_t dismec::objective::LinearClassifierImpBase< Derived >::lookup_on_line (real_t position) inline override protected virtual
Looks up the value of the objective on the line defined by the last call to project_to_line().
Parameters
position The location where the objective is calculated.
Returns
The value of objective(location + position * direction), where location and direction are the vectors passed to the last call of project_to_line().
Attention
This function may use results cached project_to_line(), so it has to be called after a call to that function. A new call to project_to_line() will change the line which is evaluated.
Implements dismec::objective::Objective.
Definition at line 142 of file linear.h.
References dismec::objective::LinearClassifierBase::costs(), dismec::objective::LinearClassifierBase::labels(), dismec::objective::LinearClassifierBase::line_interpolation(), dismec::objective::LinearClassifierImpBase< Derived >::m_Regularizer, and dismec::l2_reg_sq_hinge_detail::value_from_xTw().
project_to_line_unchecked()
template<class Derived > void dismec::objective::LinearClassifierImpBase< Derived >::project_to_line_unchecked (const HashVector & location, const DenseRealVector & direction) inline override protected virtual
The function that does the actual computation. This is called in project_to_line() after the arguments have been validated.
Implements dismec::objective::Objective.
Definition at line 147 of file linear.h.
References dismec::objective::LinearClassifierImpBase< Derived >::m_Regularizer, and dismec::objective::LinearClassifierBase::project_linear_to_line().
value_unchecked()
template<class Derived > real_t dismec::objective::LinearClassifierImpBase< Derived >::value_unchecked (const HashVector & location) inline override protected virtual
The function that does the actual value computation. This is called in value() after the argument has been validated.
Implements dismec::objective::Objective.
Definition at line 137 of file linear.h.
References dismec::objective::LinearClassifierBase::costs(), dismec::objective::LinearClassifierImpBase< Derived >::derived(), dismec::objective::LinearClassifierBase::labels(), dismec::objective::LinearClassifierImpBase< Derived >::m_Regularizer, and dismec::objective::LinearClassifierBase::x_times_w().
Member Data Documentation
m_Regularizer
template<class Derived > std::unique_ptr<Objective> dismec::objective::LinearClassifierImpBase< Derived >::m_Regularizer private
Pointer to the regularizer.
Definition at line 182 of file linear.h.
Referenced by dismec::objective::LinearClassifierImpBase< Derived >::diag_preconditioner_unchecked(), dismec::objective::LinearClassifierImpBase< Derived >::gradient_and_pre_conditioner_unchecked(), dismec::objective::LinearClassifierImpBase< Derived >::gradient_at_zero_unchecked(), dismec::objective::LinearClassifierImpBase< Derived >::gradient_unchecked(), dismec::objective::LinearClassifierImpBase< Derived >::hessian_times_direction_unchecked(), dismec::objective::LinearClassifierImpBase< Derived >::lookup_on_line(), dismec::objective::LinearClassifierImpBase< Derived >::project_to_line_unchecked(), and dismec::objective::LinearClassifierImpBase< Derived >::value_unchecked().
The documentation for this class was generated from the following file:
src/objective/linear.h