DiSMEC++: dismec::CacheHelper Class Reference
dismec::CacheHelper Class Reference
#include <hash_vector.h>
Public Member Functions
CacheHelper (Eigen::Index size)
template<class F >
const DenseRealVector & update (const HashVector &input, F &&function)
void invalidate ()
Private Attributes
VectorHash m_Input
DenseRealVector m_Output
Detailed Description
Definition at line 181 of file hash_vector.h.
Constructor & Destructor Documentation
CacheHelper()
dismec::CacheHelper::CacheHelper (Eigen::Index size) inline explicit
Definition at line 183 of file hash_vector.h.
Member Function Documentation
invalidate()
void dismec::CacheHelper::invalidate () inline
Definition at line 195 of file hash_vector.h.
References m_Input.
Referenced by dismec::objective::DenseAndSparseLinearBase::invalidate_labels().
update()
template<class F > const DenseRealVector& dismec::CacheHelper::update (const HashVector & input, F && function) inline
Definition at line 186 of file hash_vector.h.
References dismec::HashVector::get(), dismec::HashVector::hash(), m_Input, and m_Output.
Referenced by dismec::objective::DenseAndSparseLinearBase::cached_2nd_derivative(), and dismec::objective::DenseAndSparseLinearBase::cached_derivative().
Member Data Documentation
m_Input
VectorHash dismec::CacheHelper::m_Input private
Definition at line 199 of file hash_vector.h.
Referenced by invalidate(), and update().
m_Output
DenseRealVector dismec::CacheHelper::m_Output private
Definition at line 200 of file hash_vector.h.
Referenced by update().
The documentation for this class was generated from the following file:
src/utils/hash_vector.h