DiSMEC++: dismec::stats::Statistics Class Reference
dismec::stats::Statistics Class Reference abstract
TODO maybe we should solve this with a variant which does the dispatch of expected type and tag.
#include <stats_base.h>
Public Member Functions
virtual ~Statistics ()=default
void record (int integer)
void record (long integer)
void record (real_t real)
void record (const DenseRealVector &vector)
virtual std::unique_ptr< Statistics > clone () const =0
virtual void setup (const StatisticsCollection &source)
This function has to be called before the Statistics is used to collect data for the first time.
virtual void merge (const Statistics &other)=0
Merges this statistics of another one of the same type and settings.
virtual nlohmann::json to_json () const =0
Converts the statistics current value into a json object.
Private Member Functions
virtual void record_int (long integer)
virtual void record_real (real_t real)
virtual void record_vec (const DenseRealVector &vector)
Detailed Description
TODO maybe we should solve this with a variant which does the dispatch of expected type and tag.
Definition at line 65 of file stats_base.h.
Constructor & Destructor Documentation
~Statistics()
virtual dismec::stats::Statistics::~Statistics () virtual default
Member Function Documentation
clone()
virtual std::unique_ptr<Statistics> dismec::stats::Statistics::clone () const pure virtual
Implemented in dismec::stats::VectorReductionStat, dismec::stats::FullRecordStat, dismec::stats::MultiStat, dismec::stats::TaggedStat, dismec::stats::BasicStat, dismec::stats::CounterStat, and anonymous_namespace{collection.cpp}::MockStat.
merge()
virtual void dismec::stats::Statistics::merge (const Statistics & other) pure virtual
Merges this statistics of another one of the same type and settings.
This operation is used to perform the reduction of the thread-local statistics into a single global statistics. For this to be possible, the merged statistics need to have not only the same type, but also the same settings (e.g. number of bins in a histogram). This is true for the thread local copies, which are clones of one another.
Parameters
other The statistics object to be merged into this. Must be of same type and have the same settings, e.g. a clone of this.
Implemented in dismec::stats::StatImplBase< Derived >, dismec::stats::StatImplBase< VectorReductionStat >, dismec::stats::StatImplBase< TaggedStat >, dismec::stats::StatImplBase< MultiStat >, dismec::stats::StatImplBase< BasicStat >, dismec::stats::StatImplBase< FullRecordStat >, dismec::stats::StatImplBase< CounterStat >, and anonymous_namespace{collection.cpp}::MockStat.
record() [1/4]
void dismec::stats::Statistics::record (const DenseRealVector & vector) inline
Definition at line 74 of file stats_base.h.
References record_vec().
record() [2/4]
void dismec::stats::Statistics::record (int integer) inline
Definition at line 70 of file stats_base.h.
References record().
Referenced by record(), dismec::stats::BasicStat::record_int(), dismec::stats::TaggedStat::record_int(), and dismec::stats::StatImplBase< Derived >::record_vec().
record() [3/4]
void dismec::stats::Statistics::record (long integer) inline
Definition at line 72 of file stats_base.h.
References record_int().
record() [4/4]
void dismec::stats::Statistics::record (real_t real) inline
Definition at line 73 of file stats_base.h.
References record_real().
record_int()
virtual void dismec::stats::Statistics::record_int (long integer) inline private virtual
Reimplemented in dismec::stats::FullRecordStat, dismec::stats::MultiStat, dismec::stats::TaggedStat, dismec::stats::BasicStat, dismec::stats::CounterStat, and anonymous_namespace{collection.cpp}::MockStat.
Definition at line 102 of file stats_base.h.
Referenced by record().
record_real()
virtual void dismec::stats::Statistics::record_real (real_t real) inline private virtual
Reimplemented in dismec::stats::FullRecordStat, dismec::stats::MultiStat, dismec::stats::TaggedStat, and dismec::stats::BasicStat.
Definition at line 103 of file stats_base.h.
Referenced by record().
record_vec()
virtual void dismec::stats::Statistics::record_vec (const DenseRealVector & vector) inline private virtual
Reimplemented in dismec::stats::StatImplBase< Derived >, dismec::stats::StatImplBase< VectorReductionStat >, dismec::stats::StatImplBase< TaggedStat >, dismec::stats::StatImplBase< MultiStat >, dismec::stats::StatImplBase< BasicStat >, dismec::stats::StatImplBase< FullRecordStat >, dismec::stats::StatImplBase< CounterStat >, dismec::stats::MultiStat, and dismec::stats::VectorReductionStat.
Definition at line 104 of file stats_base.h.
Referenced by record().
setup()
virtual void dismec::stats::Statistics::setup (const StatisticsCollection & source) inline virtual
This function has to be called before the Statistics is used to collect data for the first time.
This will look up any tags that might be used within the statistics in source.
Exceptions
std::runtime_error if a tag is required by the statistics but cannot be found in source.
Parameters
source The statistics collection from which the tags can be read.
Reimplemented in dismec::stats::MultiStat, and dismec::stats::TaggedStat.
Definition at line 84 of file stats_base.h.
to_json()
virtual nlohmann::json dismec::stats::Statistics::to_json () const pure virtual
Converts the statistics current value into a json object.
Implemented in dismec::stats::VectorReductionStat, dismec::stats::FullRecordStat, dismec::stats::MultiStat, dismec::stats::TaggedStat, dismec::stats::BasicStat, dismec::stats::CounterStat, and anonymous_namespace{collection.cpp}::MockStat.
The documentation for this class was generated from the following file:
src/stats/stats_base.h