DiSMEC++: dismec::init::MeanOfFeaturesInitializer Class Reference
dismec::init::MeanOfFeaturesInitializer Class Reference
Public Member Functions
MeanOfFeaturesInitializer (std::shared_ptr< const DatasetBase > data, const DenseRealVector &mean_of_all, std::shared_ptr< const GenericFeatureMatrix > local_features, real_t pos, real_t neg)
void get_initial_weight (label_id_t label_id, Eigen::Ref< DenseRealVector > target, objective::Objective &objective) override
Generate an initial vector for the given label. The result should be placed in target.
Public Member Functions inherited from dismec::init::SubsetFeatureMeanInitializer
SubsetFeatureMeanInitializer (std::shared_ptr< const DatasetBase > data, const DenseRealVector &mean_of_all, std::shared_ptr< const GenericFeatureMatrix > local_features, real_t pos, real_t neg)
Public Member Functions inherited from dismec::init::WeightsInitializer
virtual ~WeightsInitializer ()=default
Public Member Functions inherited from dismec::stats::Tracked
Tracked ()
Default constructor, creates the internal stats::StatisticsCollection.
void register_stat (const std::string &name, std::unique_ptr< Statistics > stat)
Registers a tracker for the statistics name.
std::shared_ptr< StatisticsCollection > get_stats () const
Gets an ownership-sharing reference to the StatisticsCollection.
Static Private Attributes
static constexpr stats::stat_id_t STAT_POSITIVE_FACTOR {1}
static constexpr stats::stat_id_t STAT_ALL_MEAN_FACTOR {2}
static constexpr stats::stat_id_t STAT_NUM_POS {3}
static constexpr stats::stat_id_t STAT_LOSS_REDUCTION {4}
Additional Inherited Members
Protected Member Functions inherited from dismec::init::SubsetFeatureMeanInitializer
std::pair< real_t, real_t > calculate_factors (label_id_t label_id, const Eigen::Ref< DenseRealVector > &mean_of_positives)
Protected Member Functions inherited from dismec::stats::Tracked
~Tracked ()
Non-virtual destructor. Declared protected, so we don't accidentally try to do a polymorphic delete.
template<class T >
void record (stat_id_t stat, T &&value)
Record statistics. This function just forwards all its arguments to the internal StatisticsCollection.
void declare_stat (stat_id_t index, StatisticMetaData meta)
Declares a new statistics. This function just forwards all its arguments to the internal StatisticsCollection.
void declare_tag (tag_id_t index, std::string name)
Declares a new tag. This function just forwards all its arguments to the internal StatisticsCollection.
template<class... Args>
void set_tag (tag_id_t tag, long value)
Set value of tag. This function just forwards all its arguments to the internal StatisticsCollection.
template<class... Args>
auto make_timer (stat_id_t id, Args... args)
Creates a new ScopeTimer using stats::record_scope_time.
Protected Attributes inherited from dismec::init::SubsetFeatureMeanInitializer
std::shared_ptr< const DatasetBase > m_DataSet
std::shared_ptr< const GenericFeatureMatrix > m_LocalFeatures
BinaryLabelVector m_LabelBuffer
DenseRealVector m_MeanOfAll
real_t m_MeanAllNormSquared
real_t m_PosTarget
real_t m_NegTarget
Static Protected Attributes inherited from dismec::init::SubsetFeatureMeanInitializer
static constexpr stats::stat_id_t STAT_DURATION {0}
Detailed Description
Definition at line 18 of file msi.cpp.
Constructor & Destructor Documentation
MeanOfFeaturesInitializer()
MeanOfFeaturesInitializer::MeanOfFeaturesInitializer (std::shared_ptr< const DatasetBase > data, const DenseRealVector & mean_of_all, std::shared_ptr< const GenericFeatureMatrix > local_features, real_t pos, real_t neg)
Definition at line 43 of file msi.cpp.
References dismec::stats::Tracked::declare_stat(), STAT_ALL_MEAN_FACTOR, STAT_LOSS_REDUCTION, STAT_NUM_POS, and STAT_POSITIVE_FACTOR.
Member Function Documentation
get_initial_weight()
void MeanOfFeaturesInitializer::get_initial_weight (label_id_t label_id, Eigen::Ref< DenseRealVector > target, objective::Objective & objective) override virtual
Generate an initial vector for the given label. The result should be placed in target.
Implements dismec::init::WeightsInitializer.
Definition at line 55 of file msi.cpp.
References dismec::init::SubsetFeatureMeanInitializer::calculate_factors(), dismec::init::SubsetFeatureMeanInitializer::m_DataSet, dismec::init::SubsetFeatureMeanInitializer::m_LabelBuffer, dismec::init::SubsetFeatureMeanInitializer::m_LocalFeatures, dismec::init::SubsetFeatureMeanInitializer::m_MeanOfAll, dismec::stats::Tracked::make_timer(), dismec::stats::Tracked::record(), STAT_ALL_MEAN_FACTOR, dismec::init::SubsetFeatureMeanInitializer::STAT_DURATION, STAT_LOSS_REDUCTION, STAT_NUM_POS, STAT_POSITIVE_FACTOR, and dismec::types::visit().
Member Data Documentation
STAT_ALL_MEAN_FACTOR
constexpr stats::stat_id_t dismec::init::MeanOfFeaturesInitializer::STAT_ALL_MEAN_FACTOR {2} static constexpr private
Definition at line 28 of file msi.cpp.
Referenced by get_initial_weight(), and MeanOfFeaturesInitializer().
STAT_LOSS_REDUCTION
constexpr stats::stat_id_t dismec::init::MeanOfFeaturesInitializer::STAT_LOSS_REDUCTION {4} static constexpr private
Definition at line 30 of file msi.cpp.
Referenced by get_initial_weight(), and MeanOfFeaturesInitializer().
STAT_NUM_POS
constexpr stats::stat_id_t dismec::init::MeanOfFeaturesInitializer::STAT_NUM_POS {3} static constexpr private
Definition at line 29 of file msi.cpp.
Referenced by get_initial_weight(), and MeanOfFeaturesInitializer().
STAT_POSITIVE_FACTOR
constexpr stats::stat_id_t dismec::init::MeanOfFeaturesInitializer::STAT_POSITIVE_FACTOR {1} static constexpr private
Definition at line 27 of file msi.cpp.
Referenced by get_initial_weight(), and MeanOfFeaturesInitializer().
The documentation for this class was generated from the following file:
src/training/init/msi.cpp