DiSMEC++: dismec::PropensityModel Class Reference
dismec::PropensityModel Class Reference
#include <weighting.h>
Public Member Functions
PropensityModel (const DatasetBase *data, double a=0.55, double b=1.5)
double get_propensity (label_id_t label_id) const
Private Attributes
const DatasetBase * m_Data
double m_A
double m_B
double m_C
Detailed Description
Definition at line 14 of file weighting.h.
Constructor & Destructor Documentation
PropensityModel()
PropensityModel::PropensityModel (const DatasetBase * data, double a = 0.55, double b = 1.5) explicit
Definition at line 14 of file weighting.cpp.
References m_A, m_B, m_C, m_Data, and dismec::DatasetBase::num_examples().
Member Function Documentation
get_propensity()
double PropensityModel::get_propensity (label_id_t label_id) const
Definition at line 23 of file weighting.cpp.
References m_A, m_B, m_C, m_Data, and dismec::DatasetBase::num_positives().
Referenced by dismec::PropensityDownWeighting::get_negative_weight(), and dismec::PropensityWeighting::get_positive_weight().
Member Data Documentation
m_A
double dismec::PropensityModel::m_A private
Definition at line 20 of file weighting.h.
Referenced by get_propensity(), and PropensityModel().
m_B
double dismec::PropensityModel::m_B private
Definition at line 21 of file weighting.h.
Referenced by get_propensity(), and PropensityModel().
m_C
double dismec::PropensityModel::m_C private
Definition at line 22 of file weighting.h.
Referenced by get_propensity(), and PropensityModel().
m_Data
const DatasetBase* dismec::PropensityModel::m_Data private
Definition at line 19 of file weighting.h.
Referenced by get_propensity(), and PropensityModel().
The documentation for this class was generated from the following files:
src/training/weighting.h
src/training/weighting.cpp