DiSMEC++: dismec::prediction::MetricCollectionInterface Class Reference
dismec::prediction::MetricCollectionInterface Class Reference abstract
Base class for all metrics that can be calculated during the evaluation phase.
#include <metrics.h>
Public Types
using gt_info_vec = std::vector< sTrueLabelInfo >
using pd_info_vec = std::vector< sPredLabelInfo >
Public Member Functions
MetricCollectionInterface (long num_labels)
virtual ~MetricCollectionInterface ()=default
long num_labels () const
Gets the number of labels.
virtual void update (const pd_info_vec &prediction, const gt_info_vec &labels)=0
virtual void reduce (const MetricCollectionInterface &other)=0
virtual std::unique_ptr< MetricCollectionInterface > clone () const =0
Private Attributes
long m_NumLabels
Detailed Description
Base class for all metrics that can be calculated during the evaluation phase.
This is the interface that is used by the evaluation task to handle the individual metrics. This interface handles the data collection part. It provides the following operations: 1) Accumulating a new prediction into the metric 2) reducing multiple instances of the metric interface. The second operation is necessary to allow for efficient multithreaded calculation of the metric.
Definition at line 28 of file metrics.h.
Member Typedef Documentation
gt_info_vec
using dismec::prediction::MetricCollectionInterface::gt_info_vec = std::vector<sTrueLabelInfo>
Definition at line 30 of file metrics.h.
pd_info_vec
using dismec::prediction::MetricCollectionInterface::pd_info_vec = std::vector<sPredLabelInfo>
Definition at line 31 of file metrics.h.
Constructor & Destructor Documentation
MetricCollectionInterface()
MetricCollectionInterface::MetricCollectionInterface (long num_labels) explicit
Constructor, gets the total number of labels, since these cannot be inferred from the sparse prediction and ground-truth arrays in the update step.
Definition at line 15 of file metrics.cpp.
References num_labels(), and THROW_EXCEPTION.
~MetricCollectionInterface()
virtual dismec::prediction::MetricCollectionInterface::~MetricCollectionInterface () virtual default
Member Function Documentation
clone()
virtual std::unique_ptr<MetricCollectionInterface> dismec::prediction::MetricCollectionInterface::clone () const pure virtual
Implemented in dismec::prediction::AbandonmentAtK, dismec::prediction::InstanceRankedPositives, and dismec::prediction::ConfusionMatrixRecorder.
num_labels()
long dismec::prediction::MetricCollectionInterface::num_labels () const inline
Gets the number of labels.
Definition at line 38 of file metrics.h.
References m_NumLabels.
Referenced by dismec::prediction::ConfusionMatrixRecorder::clone(), dismec::prediction::InstanceRankedPositives::clone(), dismec::prediction::AbandonmentAtK::clone(), dismec::prediction::ConfusionMatrixRecorder::ConfusionMatrixRecorder(), dismec::prediction::MacroMetricReporter::get_values(), MetricCollectionInterface(), and dismec::prediction::ConfusionMatrixRecorder::reduce().
reduce()
virtual void dismec::prediction::MetricCollectionInterface::reduce (const MetricCollectionInterface & other) pure virtual
Implemented in dismec::prediction::InstanceAveragedMetric, and dismec::prediction::ConfusionMatrixRecorder.
update()
virtual void dismec::prediction::MetricCollectionInterface::update (const pd_info_vec & prediction, const gt_info_vec & labels) pure virtual
Implemented in dismec::prediction::AbandonmentAtK, dismec::prediction::InstanceRankedPositives, and dismec::prediction::ConfusionMatrixRecorder.
Member Data Documentation
m_NumLabels
long dismec::prediction::MetricCollectionInterface::m_NumLabels private
Definition at line 44 of file metrics.h.
Referenced by num_labels().
The documentation for this class was generated from the following files:
src/prediction/metrics.h
src/prediction/metrics.cpp