DiSMEC++: src/stats/collection.cpp File Reference
collection.cpp File Reference
#include "collection.h"
#include "spdlog/spdlog.h"
#include "utils/conversion.h"
#include "doctest.h"
#include "nlohmann/json.hpp"
Classes
struct anonymous_namespace{collection.cpp}::MockStat
Namespaces
anonymous_namespace{collection.cpp}
Functions
stat_id_t anonymous_namespace{collection.cpp}::str_to_id (const std::string &str, const std::vector< StatisticMetaData > &names)
TEST_CASE ("check errors for stats")
TEST_CASE ("check errors for tags")
TEST_CASE ("register stat")
TEST_CASE ("enable-disable")
TEST_CASE ("recording")
TEST_CASE ("tag handling")
TEST_CASE ("tag sharing")
Function Documentation
TEST_CASE() [1/7]
TEST_CASE ("check errors for stats")
Definition at line 152 of file collection.cpp.
References dismec::stats::StatisticsCollection::declare_stat(), dismec::stats::StatisticsCollection::disable(), dismec::stats::StatisticsCollection::enable(), dismec::stats::StatisticsCollection::get_stat(), dismec::stats::StatisticsCollection::get_statistics_meta(), dismec::stats::StatisticsCollection::is_enabled_by_name(), and dismec::stats::StatisticsCollection::register_stat().
TEST_CASE() [2/7]
TEST_CASE ("check errors for tags")
Definition at line 177 of file collection.cpp.
References dismec::stats::StatisticsCollection::declare_tag(), dismec::stats::StatisticsCollection::get_all_tags(), and dismec::stats::StatisticsCollection::get_tag_by_name().
TEST_CASE() [3/7]
TEST_CASE ("enable-disable")
Definition at line 218 of file collection.cpp.
References dismec::stats::StatisticsCollection::declare_stat(), dismec::stats::StatisticsCollection::disable(), dismec::stats::StatisticsCollection::enable(), dismec::stats::StatisticsCollection::is_enabled(), dismec::stats::StatisticsCollection::is_enabled_by_name(), and dismec::stats::StatisticsCollection::register_stat().
TEST_CASE() [4/7]
TEST_CASE ("recording")
Definition at line 247 of file collection.cpp.
References dismec::stats::StatisticsCollection::declare_stat(), dismec::stats::StatisticsCollection::disable(), dismec::stats::StatisticsCollection::get_stat(), dismec::stats::StatisticsCollection::record(), and dismec::stats::StatisticsCollection::register_stat().
TEST_CASE() [5/7]
TEST_CASE ("register stat")
Definition at line 194 of file collection.cpp.
References dismec::stats::StatisticsCollection::declare_stat(), dismec::stats::StatisticsCollection::get_stat(), dismec::stats::StatisticsCollection::has_stat(), dismec::stats::StatisticsCollection::is_enabled_by_name(), and dismec::stats::StatisticsCollection::register_stat().
TEST_CASE() [6/7]
TEST_CASE ("tag handling")
Definition at line 266 of file collection.cpp.
References dismec::stats::StatisticsCollection::declare_tag(), dismec::stats::TagContainer::get_name(), dismec::stats::StatisticsCollection::get_tag_by_name(), dismec::stats::TagContainer::get_value(), and dismec::stats::StatisticsCollection::set_tag().
TEST_CASE() [7/7]
TEST_CASE ("tag sharing")
TODO we really should have scoped names here!
Definition at line 282 of file collection.cpp.
References dismec::stats::StatisticsCollection::declare_tag(), dismec::stats::StatisticsCollection::get_tag_by_name(), dismec::stats::StatisticsCollection::provide_tags(), and dismec::stats::StatisticsCollection::set_tag().