DiSMEC++: src/objective/generic_linear.cpp File Reference
generic_linear.cpp File Reference
#include "generic_linear.h"
#include "utils/eigen_generic.h"
#include "utils/throw_error.h"
#include "stats/collection.h"
#include "margin_losses.h"
#include "doctest.h"
#include "regularizers_imp.h"
#include "reg_sq_hinge.h"
Namespaces
anonymous_namespace{generic_linear.cpp}
Functions
template<class Phi , class... Args>
std::unique_ptr< GenericLinearClassifier > anonymous_namespace{generic_linear.cpp}::make_gen_lin_classifier (std::shared_ptr< const GenericFeatureMatrix > X, std::unique_ptr< objective::Objective > regularizer, Args... args)
void anonymous_namespace{generic_linear.cpp}::test_equivalence (objective::Objective &a, objective::Objective &b, const HashVector &input)
TEST_CASE ("sparse/dense equivalence")
TEST_CASE ("generic squared hinge")
Variables
constexpr const stat_id_t anonymous_namespace{generic_linear.cpp}::STAT_GRAD_SPARSITY {8}
Function Documentation
TEST_CASE() [1/2]
TEST_CASE ("generic squared hinge")
Definition at line 312 of file generic_linear.cpp.
References dismec::objective::make_squared_hinge().
TEST_CASE() [2/2]
TEST_CASE ("sparse/dense equivalence")
Definition at line 236 of file generic_linear.cpp.
References dismec::objective::make_squared_hinge(), and anonymous_namespace{generic_linear.cpp}::test_equivalence().