DiSMEC++: src/tools/labelstats.cpp File Reference
labelstats.cpp File Reference
#include "io/xmc.h"
#include "data/data.h"
#include "nlohmann/json.hpp"
#include "CLI/CLI.hpp"
#include "utils/conversion.h"
#include <numeric>
#include <random>
Typedefs
using json = nlohmann::json
Functions
double obesity (const std::vector< long > &values, int num_samples)
int main (int argc, const char **argv)
Typedef Documentation
json
using json = nlohmann::json
Definition at line 14 of file labelstats.cpp.
Function Documentation
main()
int main (int argc, const char ** argv)
Definition at line 18 of file labelstats.cpp.
References obesity(), dismec::io::ONE_BASED, dismec::io::read_xmc_dataset(), dismec::ssize(), dismec::io::model::to_string(), and dismec::io::ZERO_BASED.
obesity()
double obesity (const std::vector< long > & values, int num_samples)
Definition at line 77 of file labelstats.cpp.
References dismec::ssize().
Referenced by main().