DiSMEC++: dismec::confusion_matrix_detail Namespace Reference
dismec::confusion_matrix_detail Namespace Reference
Classes
struct ConfusionMatrixBase
Functions
template<class T >
constexpr ConfusionMatrixBase< T > & operator+= (ConfusionMatrixBase< T > &lhs, const ConfusionMatrixBase< T > &rhs)
template<class T >
constexpr T predicted_positives (const ConfusionMatrixBase< T > &matrix)
template<class T >
constexpr T predicted_negatives (const ConfusionMatrixBase< T > &matrix)
template<class T >
constexpr T positives (const ConfusionMatrixBase< T > &matrix)
template<class T >
constexpr T negatives (const ConfusionMatrixBase< T > &matrix)
template<class T >
constexpr T total_samples (const ConfusionMatrixBase< T > &matrix)
template<class Scalar >
constexpr double save_div (Scalar num, Scalar den)
template<class T >
constexpr double true_positive_fraction (const ConfusionMatrixBase< T > &matrix)
template<class T >
constexpr double false_positive_fraction (const ConfusionMatrixBase< T > &matrix)
template<class T >
constexpr double true_negative_fraction (const ConfusionMatrixBase< T > &matrix)
template<class T >
constexpr double false_negative_fraction (const ConfusionMatrixBase< T > &matrix)
template<class T >
constexpr double accuracy (const ConfusionMatrixBase< T > &matrix)
template<class T >
constexpr double prevalence (const ConfusionMatrixBase< T > &matrix)
template<class T >
constexpr double positive_predictive_value (const ConfusionMatrixBase< T > &matrix)
template<class T >
constexpr double false_discovery_rate (const ConfusionMatrixBase< T > &matrix)
template<class T >
constexpr double negative_predictive_value (const ConfusionMatrixBase< T > &matrix)
template<class T >
constexpr double false_omission_rate (const ConfusionMatrixBase< T > &matrix)
template<class T >
constexpr double true_positive_rate (const ConfusionMatrixBase< T > &matrix)
template<class T >
constexpr double false_negative_rate (const ConfusionMatrixBase< T > &matrix)
template<class T >
constexpr double false_positive_rate (const ConfusionMatrixBase< T > &matrix)
template<class T >
constexpr double true_negative_rate (const ConfusionMatrixBase< T > &matrix)
template<class T >
constexpr double precision (const ConfusionMatrixBase< T > &matrix)
template<class T >
constexpr double recall (const ConfusionMatrixBase< T > &matrix)
template<class T >
constexpr double sensitivity (const ConfusionMatrixBase< T > &matrix)
template<class T >
constexpr double specificity (const ConfusionMatrixBase< T > &matrix)
template<class T >
constexpr double informedness (const ConfusionMatrixBase< T > &matrix)
template<class T >
constexpr double markedness (const ConfusionMatrixBase< T > &matrix)
template<class T >
constexpr double fowlkes_mallows (const ConfusionMatrixBase< T > &matrix)
template<class T >
constexpr double positive_likelihood_ratio (const ConfusionMatrixBase< T > &matrix)
template<class T >
constexpr double negative_likelihood_ratio (const ConfusionMatrixBase< T > &matrix)
template<class T >
constexpr double diagnostic_odds_ratio (const ConfusionMatrixBase< T > &matrix)
template<class T >
constexpr double matthews (const ConfusionMatrixBase< T > &matrix)
template<class T >
constexpr double balanced_accuracy (const ConfusionMatrixBase< T > &matrix)
template<class T >
constexpr double f_beta (const ConfusionMatrixBase< T > &matrix, double beta)
Function Documentation
accuracy()
template<class T > constexpr double dismec::confusion_matrix_detail::accuracy (const ConfusionMatrixBase< T > & matrix) constexpr
Definition at line 86 of file confusion_matrix.h.
References save_div(), total_samples(), dismec::confusion_matrix_detail::ConfusionMatrixBase< T >::TrueNegatives, and dismec::confusion_matrix_detail::ConfusionMatrixBase< T >::TruePositives.
balanced_accuracy()
template<class T > constexpr double dismec::confusion_matrix_detail::balanced_accuracy (const ConfusionMatrixBase< T > & matrix) constexpr
Definition at line 200 of file confusion_matrix.h.
References true_negative_rate(), and true_positive_rate().
diagnostic_odds_ratio()
template<class T > constexpr double dismec::confusion_matrix_detail::diagnostic_odds_ratio (const ConfusionMatrixBase< T > & matrix) constexpr
Definition at line 188 of file confusion_matrix.h.
References negative_likelihood_ratio(), positive_likelihood_ratio(), and save_div().
f_beta()
template<class T > constexpr double dismec::confusion_matrix_detail::f_beta (const ConfusionMatrixBase< T > & matrix, double beta) constexpr
Definition at line 205 of file confusion_matrix.h.
References dismec::confusion_matrix_detail::ConfusionMatrixBase< T >::FalseNegatives, dismec::confusion_matrix_detail::ConfusionMatrixBase< T >::FalsePositives, and dismec::confusion_matrix_detail::ConfusionMatrixBase< T >::TruePositives.
Referenced by dismec::prediction::MacroMetricReporter::add_f_measure().
false_discovery_rate()
template<class T > constexpr double dismec::confusion_matrix_detail::false_discovery_rate (const ConfusionMatrixBase< T > & matrix) constexpr
Definition at line 103 of file confusion_matrix.h.
References positive_predictive_value().
Referenced by matthews().
false_negative_fraction()
template<class T > constexpr double dismec::confusion_matrix_detail::false_negative_fraction (const ConfusionMatrixBase< T > & matrix) constexpr
Definition at line 81 of file confusion_matrix.h.
References dismec::confusion_matrix_detail::ConfusionMatrixBase< T >::FalseNegatives, save_div(), and total_samples().
false_negative_rate()
template<class T > constexpr double dismec::confusion_matrix_detail::false_negative_rate (const ConfusionMatrixBase< T > & matrix) constexpr
Definition at line 124 of file confusion_matrix.h.
References dismec::confusion_matrix_detail::ConfusionMatrixBase< T >::FalseNegatives, positives(), and save_div().
Referenced by matthews(), and negative_likelihood_ratio().
false_omission_rate()
template<class T > constexpr double dismec::confusion_matrix_detail::false_omission_rate (const ConfusionMatrixBase< T > & matrix) constexpr
Definition at line 113 of file confusion_matrix.h.
References negative_predictive_value().
Referenced by matthews().
false_positive_fraction()
template<class T > constexpr double dismec::confusion_matrix_detail::false_positive_fraction (const ConfusionMatrixBase< T > & matrix) constexpr
Definition at line 71 of file confusion_matrix.h.
References dismec::confusion_matrix_detail::ConfusionMatrixBase< T >::FalsePositives, save_div(), and total_samples().
false_positive_rate()
template<class T > constexpr double dismec::confusion_matrix_detail::false_positive_rate (const ConfusionMatrixBase< T > & matrix) constexpr
Definition at line 129 of file confusion_matrix.h.
References dismec::confusion_matrix_detail::ConfusionMatrixBase< T >::FalsePositives, negatives(), and save_div().
Referenced by matthews(), and positive_likelihood_ratio().
fowlkes_mallows()
template<class T > constexpr double dismec::confusion_matrix_detail::fowlkes_mallows (const ConfusionMatrixBase< T > & matrix) constexpr
Definition at line 173 of file confusion_matrix.h.
References positive_predictive_value(), and true_positive_rate().
informedness()
template<class T > constexpr double dismec::confusion_matrix_detail::informedness (const ConfusionMatrixBase< T > & matrix) constexpr
Definition at line 163 of file confusion_matrix.h.
References true_negative_rate(), and true_positive_rate().
markedness()
template<class T > constexpr double dismec::confusion_matrix_detail::markedness (const ConfusionMatrixBase< T > & matrix) constexpr
Definition at line 168 of file confusion_matrix.h.
References negative_predictive_value(), and positive_predictive_value().
matthews()
template<class T > constexpr double dismec::confusion_matrix_detail::matthews (const ConfusionMatrixBase< T > & matrix) constexpr
Definition at line 193 of file confusion_matrix.h.
References false_discovery_rate(), false_negative_rate(), false_omission_rate(), false_positive_rate(), negative_predictive_value(), positive_predictive_value(), true_negative_rate(), and true_positive_rate().
negative_likelihood_ratio()
template<class T > constexpr double dismec::confusion_matrix_detail::negative_likelihood_ratio (const ConfusionMatrixBase< T > & matrix) constexpr
Definition at line 183 of file confusion_matrix.h.
References false_negative_rate(), save_div(), and true_negative_rate().
Referenced by diagnostic_odds_ratio().
negative_predictive_value()
template<class T > constexpr double dismec::confusion_matrix_detail::negative_predictive_value (const ConfusionMatrixBase< T > & matrix) constexpr
Definition at line 108 of file confusion_matrix.h.
References predicted_negatives(), save_div(), and dismec::confusion_matrix_detail::ConfusionMatrixBase< T >::TrueNegatives.
Referenced by false_omission_rate(), markedness(), and matthews().
negatives()
template<class T > constexpr T dismec::confusion_matrix_detail::negatives (const ConfusionMatrixBase< T > & matrix) constexpr
Definition at line 47 of file confusion_matrix.h.
References dismec::confusion_matrix_detail::ConfusionMatrixBase< T >::FalsePositives, and dismec::confusion_matrix_detail::ConfusionMatrixBase< T >::TrueNegatives.
Referenced by false_positive_rate(), and true_negative_rate().
operator+=()
template<class T > constexpr ConfusionMatrixBase<T>& dismec::confusion_matrix_detail::operator+= (ConfusionMatrixBase< T > & lhs, const ConfusionMatrixBase< T > & rhs) constexpr
Definition at line 21 of file confusion_matrix.h.
References dismec::confusion_matrix_detail::ConfusionMatrixBase< T >::FalseNegatives, dismec::confusion_matrix_detail::ConfusionMatrixBase< T >::FalsePositives, dismec::confusion_matrix_detail::ConfusionMatrixBase< T >::TrueNegatives, and dismec::confusion_matrix_detail::ConfusionMatrixBase< T >::TruePositives.
positive_likelihood_ratio()
template<class T > constexpr double dismec::confusion_matrix_detail::positive_likelihood_ratio (const ConfusionMatrixBase< T > & matrix) constexpr
Definition at line 178 of file confusion_matrix.h.
References false_positive_rate(), save_div(), and true_positive_rate().
Referenced by diagnostic_odds_ratio().
positive_predictive_value()
template<class T > constexpr double dismec::confusion_matrix_detail::positive_predictive_value (const ConfusionMatrixBase< T > & matrix) constexpr
Definition at line 98 of file confusion_matrix.h.
References predicted_positives(), save_div(), and dismec::confusion_matrix_detail::ConfusionMatrixBase< T >::TruePositives.
Referenced by false_discovery_rate(), fowlkes_mallows(), markedness(), matthews(), and precision().
positives()
template<class T > constexpr T dismec::confusion_matrix_detail::positives (const ConfusionMatrixBase< T > & matrix) constexpr
Definition at line 42 of file confusion_matrix.h.
References dismec::confusion_matrix_detail::ConfusionMatrixBase< T >::FalseNegatives, and dismec::confusion_matrix_detail::ConfusionMatrixBase< T >::TruePositives.
Referenced by false_negative_rate(), prevalence(), register_dataset(), and true_positive_rate().
precision()
template<class T > constexpr double dismec::confusion_matrix_detail::precision (const ConfusionMatrixBase< T > & matrix) constexpr
Definition at line 141 of file confusion_matrix.h.
References positive_predictive_value().
Referenced by PYBIND11_MODULE(), anonymous_namespace{py_data.cpp}::save_xmc(), and dismec::io::save_xmc_dataset().
predicted_negatives()
template<class T > constexpr T dismec::confusion_matrix_detail::predicted_negatives (const ConfusionMatrixBase< T > & matrix) constexpr
Definition at line 37 of file confusion_matrix.h.
References dismec::confusion_matrix_detail::ConfusionMatrixBase< T >::FalseNegatives, and dismec::confusion_matrix_detail::ConfusionMatrixBase< T >::TrueNegatives.
Referenced by negative_predictive_value().
predicted_positives()
template<class T > constexpr T dismec::confusion_matrix_detail::predicted_positives (const ConfusionMatrixBase< T > & matrix) constexpr
Definition at line 32 of file confusion_matrix.h.
References dismec::confusion_matrix_detail::ConfusionMatrixBase< T >::FalsePositives, and dismec::confusion_matrix_detail::ConfusionMatrixBase< T >::TruePositives.
Referenced by positive_predictive_value().
prevalence()
template<class T > constexpr double dismec::confusion_matrix_detail::prevalence (const ConfusionMatrixBase< T > & matrix) constexpr
Definition at line 91 of file confusion_matrix.h.
References positives(), save_div(), and total_samples().
recall()
template<class T > constexpr double dismec::confusion_matrix_detail::recall (const ConfusionMatrixBase< T > & matrix) constexpr
Definition at line 146 of file confusion_matrix.h.
References true_positive_rate().
Referenced by dismec::prediction::MacroMetricReporter::add_coverage().
save_div()
template<class Scalar > constexpr double dismec::confusion_matrix_detail::save_div (Scalar num, Scalar den) constexpr
Division that returns 0.0 whenever the numerator is 0, even if the denominator is 0. This means that 0/0 := 0 for the purpose of this operation. Any other division by zero will result in +-inf.
Definition at line 59 of file confusion_matrix.h.
Referenced by accuracy(), diagnostic_odds_ratio(), false_negative_fraction(), false_negative_rate(), false_positive_fraction(), false_positive_rate(), negative_likelihood_ratio(), negative_predictive_value(), positive_likelihood_ratio(), positive_predictive_value(), prevalence(), true_negative_fraction(), true_negative_rate(), true_positive_fraction(), and true_positive_rate().
sensitivity()
template<class T > constexpr double dismec::confusion_matrix_detail::sensitivity (const ConfusionMatrixBase< T > & matrix) constexpr
Definition at line 151 of file confusion_matrix.h.
References true_positive_rate().
specificity()
template<class T > constexpr double dismec::confusion_matrix_detail::specificity (const ConfusionMatrixBase< T > & matrix) constexpr
Definition at line 156 of file confusion_matrix.h.
References true_negative_rate().
total_samples()
template<class T > constexpr T dismec::confusion_matrix_detail::total_samples (const ConfusionMatrixBase< T > & matrix) constexpr
Definition at line 52 of file confusion_matrix.h.
References dismec::confusion_matrix_detail::ConfusionMatrixBase< T >::FalseNegatives, dismec::confusion_matrix_detail::ConfusionMatrixBase< T >::FalsePositives, dismec::confusion_matrix_detail::ConfusionMatrixBase< T >::TrueNegatives, and dismec::confusion_matrix_detail::ConfusionMatrixBase< T >::TruePositives.
Referenced by accuracy(), false_negative_fraction(), false_positive_fraction(), prevalence(), true_negative_fraction(), and true_positive_fraction().
true_negative_fraction()
template<class T > constexpr double dismec::confusion_matrix_detail::true_negative_fraction (const ConfusionMatrixBase< T > & matrix) constexpr
Definition at line 76 of file confusion_matrix.h.
References save_div(), total_samples(), and dismec::confusion_matrix_detail::ConfusionMatrixBase< T >::TrueNegatives.
true_negative_rate()
template<class T > constexpr double dismec::confusion_matrix_detail::true_negative_rate (const ConfusionMatrixBase< T > & matrix) constexpr
Definition at line 134 of file confusion_matrix.h.
References negatives(), save_div(), and dismec::confusion_matrix_detail::ConfusionMatrixBase< T >::TrueNegatives.
Referenced by balanced_accuracy(), informedness(), matthews(), negative_likelihood_ratio(), and specificity().
true_positive_fraction()
template<class T > constexpr double dismec::confusion_matrix_detail::true_positive_fraction (const ConfusionMatrixBase< T > & matrix) constexpr
Definition at line 66 of file confusion_matrix.h.
References save_div(), total_samples(), and dismec::confusion_matrix_detail::ConfusionMatrixBase< T >::TruePositives.
true_positive_rate()
template<class T > constexpr double dismec::confusion_matrix_detail::true_positive_rate (const ConfusionMatrixBase< T > & matrix) constexpr
Definition at line 119 of file confusion_matrix.h.
References positives(), save_div(), and dismec::confusion_matrix_detail::ConfusionMatrixBase< T >::TruePositives.
Referenced by balanced_accuracy(), fowlkes_mallows(), informedness(), matthews(), positive_likelihood_ratio(), recall(), and sensitivity().