DiSMEC++: anonymous_namespace{metrics.cpp} Namespace Reference
anonymous_namespace{metrics.cpp} Namespace Reference
Typedefs
using pred_mat_t = Eigen::Matrix< long, 1, Eigen::Dynamic >
Functions
std::vector< double > uniform_weights (long k)
constexpr const char * reduction_name (MacroMetricReporter::ReductionType type)
auto make_labels (std::initializer_list< long > init_list)
template<class T >
void update_metric (T &target, std::initializer_list< long > prediction, std::initializer_list< long > labels)
Typedef Documentation
pred_mat_t
using anonymous_namespace{metrics.cpp}::pred_mat_t = typedef Eigen::Matrix<long, 1, Eigen::Dynamic>
Definition at line 313 of file metrics.cpp.
Function Documentation
make_labels()
auto anonymous_namespace{metrics.cpp}::make_labels (std::initializer_list< long > init_list)
Definition at line 314 of file metrics.cpp.
Referenced by update_metric().
reduction_name()
constexpr const char* anonymous_namespace{metrics.cpp}::reduction_name (MacroMetricReporter::ReductionType type) constexpr
Definition at line 195 of file metrics.cpp.
References dismec::prediction::MacroMetricReporter::MACRO, and dismec::prediction::MacroMetricReporter::MICRO.
Referenced by dismec::prediction::MacroMetricReporter::add_f_measure(), and dismec::prediction::MacroMetricReporter::add_reduction_helper().
uniform_weights()
std::vector<double> anonymous_namespace{metrics.cpp}::uniform_weights (long k)
Definition at line 92 of file metrics.cpp.
update_metric()
template<class T > void anonymous_namespace{metrics.cpp}::update_metric (T & target, std::initializer_list< long > prediction, std::initializer_list< long > labels)
Definition at line 324 of file metrics.cpp.
References make_labels(), and dismec::prediction::EvaluateMetrics::process_prediction().
Referenced by TEST_CASE().