DiSMEC++: anonymous_namespace{py_data.cpp} Namespace Reference
anonymous_namespace{py_data.cpp} Namespace Reference
Functions
auto num_positives (const DatasetBase &ds, long label)
auto num_negatives (const DatasetBase &ds, long label)
auto get_labels (const DatasetBase &ds, long id)
auto get_features (const DatasetBase &ds)
auto set_features_sparse (DatasetBase &ds, SparseFeatures features)
auto set_features_dense (DatasetBase &ds, DenseFeatures features)
PyDataSet load_xmc (const std::filesystem::path &source_file, bool one_based_indexing)
void save_xmc (const std::filesystem::path &target_file, const DatasetBase &ds, int precision)
PyDataSet load_slice (const std::filesystem::path &features_file, const std::filesystem::path &labels_file)
Function Documentation
get_features()
auto anonymous_namespace{py_data.cpp}::get_features (const DatasetBase & ds)
Definition at line 28 of file py_data.cpp.
References dismec::DatasetBase::get_features().
Referenced by register_dataset().
get_labels()
auto anonymous_namespace{py_data.cpp}::get_labels (const DatasetBase & ds, long id)
Definition at line 25 of file py_data.cpp.
References dismec::DatasetBase::get_labels().
Referenced by register_dataset().
load_slice()
PyDataSet anonymous_namespace{py_data.cpp}::load_slice (const std::filesystem::path & features_file, const std::filesystem::path & labels_file)
Definition at line 50 of file py_data.cpp.
References dismec::io::read_slice_dataset(), and wrap_shared().
Referenced by register_dataset().
load_xmc()
PyDataSet anonymous_namespace{py_data.cpp}::load_xmc (const std::filesystem::path & source_file, bool one_based_indexing)
Definition at line 38 of file py_data.cpp.
References dismec::io::ONE_BASED, dismec::io::read_xmc_dataset(), wrap_shared(), and dismec::io::ZERO_BASED.
Referenced by register_dataset().
num_negatives()
auto anonymous_namespace{py_data.cpp}::num_negatives (const DatasetBase & ds, long label)
Definition at line 22 of file py_data.cpp.
References dismec::DatasetBase::num_negatives().
Referenced by register_dataset().
num_positives()
auto anonymous_namespace{py_data.cpp}::num_positives (const DatasetBase & ds, long label)
Definition at line 19 of file py_data.cpp.
References dismec::DatasetBase::num_positives().
Referenced by register_dataset().
save_xmc()
void anonymous_namespace{py_data.cpp}::save_xmc (const std::filesystem::path & target_file, const DatasetBase & ds, int precision)
Definition at line 46 of file py_data.cpp.
References dismec::confusion_matrix_detail::precision(), and dismec::io::save_xmc_dataset().
Referenced by register_dataset().
set_features_dense()
auto anonymous_namespace{py_data.cpp}::set_features_dense (DatasetBase & ds, DenseFeatures features)
Definition at line 34 of file py_data.cpp.
References dismec::DatasetBase::edit_features().
Referenced by register_dataset().
set_features_sparse()
auto anonymous_namespace{py_data.cpp}::set_features_sparse (DatasetBase & ds, SparseFeatures features)
Definition at line 31 of file py_data.cpp.
References dismec::DatasetBase::edit_features().
Referenced by register_dataset().