DiSMEC++: anonymous_namespace{generic_linear.cpp} Namespace Reference
anonymous_namespace{generic_linear.cpp} Namespace Reference
Functions
template<class Phi , class... Args>
std::unique_ptr< GenericLinearClassifier > make_gen_lin_classifier (std::shared_ptr< const GenericFeatureMatrix > X, std::unique_ptr< objective::Objective > regularizer, Args... args)
void test_equivalence (objective::Objective &a, objective::Objective &b, const HashVector &input)
Variables
constexpr const stat_id_t STAT_GRAD_SPARSITY {8}
Function Documentation
make_gen_lin_classifier()
template<class Phi , class... Args> std::unique_ptr<GenericLinearClassifier> anonymous_namespace{generic_linear.cpp}::make_gen_lin_classifier (std::shared_ptr< const GenericFeatureMatrix > X, std::unique_ptr< objective::Objective > regularizer, Args... args)
Definition at line 167 of file generic_linear.cpp.
test_equivalence()
void anonymous_namespace{generic_linear.cpp}::test_equivalence (objective::Objective & a, objective::Objective & b, const HashVector & input)
Definition at line 199 of file generic_linear.cpp.
References dismec::objective::Objective::diag_preconditioner(), dismec::objective::Objective::gradient(), dismec::objective::Objective::gradient_and_pre_conditioner(), dismec::objective::Objective::gradient_at_zero(), dismec::objective::Objective::hessian_times_direction(), and dismec::objective::Objective::value().
Referenced by TEST_CASE().
Variable Documentation
STAT_GRAD_SPARSITY
constexpr const stat_id_t anonymous_namespace{generic_linear.cpp}::STAT_GRAD_SPARSITY {8} constexpr
Definition at line 17 of file generic_linear.cpp.
Referenced by dismec::objective::GenericLinearClassifier::cached_derivative(), and dismec::objective::GenericLinearClassifier::GenericLinearClassifier().