DiSMEC++: anonymous_namespace{regularizers_imp.cpp} Namespace Reference
anonymous_namespace{regularizers_imp.cpp} Namespace Reference
Functions
DenseRealVector make_vec (std::initializer_list< real_t > values)
void verify_line_search (objective::Objective &reg)
void verify_bias (objective::Objective &full, objective::Objective &no_bias)
Function Documentation
make_vec()
DenseRealVector anonymous_namespace{regularizers_imp.cpp}::make_vec (std::initializer_list< real_t > values)
Definition at line 147 of file regularizers_imp.cpp.
References dismec::ssize().
Referenced by TEST_CASE(), verify_bias(), and verify_line_search().
verify_bias()
void anonymous_namespace{regularizers_imp.cpp}::verify_bias (objective::Objective & full, objective::Objective & no_bias)
Definition at line 170 of file regularizers_imp.cpp.
References dismec::objective::Objective::gradient(), dismec::objective::Objective::hessian_times_direction(), make_vec(), and dismec::objective::Objective::value().
Referenced by TEST_CASE().
verify_line_search()
void anonymous_namespace{regularizers_imp.cpp}::verify_line_search (objective::Objective & reg)
Definition at line 157 of file regularizers_imp.cpp.
References dismec::objective::Objective::lookup_on_line(), make_vec(), dismec::objective::Objective::project_to_line(), and dismec::objective::Objective::value().
Referenced by TEST_CASE().