DiSMEC++: anonymous_namespace{py_train.cpp} Namespace Reference
anonymous_namespace{py_train.cpp} Namespace Reference
Functions
auto get_positive_weight (const WeightingScheme &pds, long label)
auto get_negative_weight (const WeightingScheme &pds, long label)
PyWeighting make_constant (double pos, double neg)
PyWeighting make_propensity (const DatasetBase &data, double a, double b)
PyWeighting make_custom (DenseRealVector pos, DenseRealVector neg)
Function Documentation
get_negative_weight()
auto anonymous_namespace{py_train.cpp}::get_negative_weight (const WeightingScheme & pds, long label)
Definition at line 67 of file py_train.cpp.
References dismec::WeightingScheme::get_negative_weight().
Referenced by register_weighting().
get_positive_weight()
auto anonymous_namespace{py_train.cpp}::get_positive_weight (const WeightingScheme & pds, long label)
Definition at line 64 of file py_train.cpp.
References dismec::WeightingScheme::get_positive_weight().
Referenced by register_weighting().
make_constant()
PyWeighting anonymous_namespace{py_train.cpp}::make_constant (double pos, double neg)
Definition at line 71 of file py_train.cpp.
Referenced by register_weighting().
make_custom()
PyWeighting anonymous_namespace{py_train.cpp}::make_custom (DenseRealVector pos, DenseRealVector neg)
Definition at line 77 of file py_train.cpp.
Referenced by register_weighting().
make_propensity()
PyWeighting anonymous_namespace{py_train.cpp}::make_propensity (const DatasetBase & data, double a, double b)
Definition at line 74 of file py_train.cpp.
Referenced by register_weighting().