DiSMEC++: dismec::types Namespace Reference
dismec::types Namespace Reference
Namespaces
type_helpers
Classes
class GenericMatrixRef
class GenericMatrix
class GenericVectorRef
class VarWrapBase
class EigenVariantWrapper
class RefVariant
Typedefs
template<class T >
using GenericVector = GenericMatrix< DenseVector< T >, SparseVector< T > >
Functions
template<class T >
decltype(auto) unpack_variant_wrapper (T &&source, std::enable_if_t<!is_variant_wrapper< T >, void * > dispatch=nullptr)
template<class T >
decltype(auto) unpack_variant_wrapper (T &&source, std::enable_if_t< is_variant_wrapper< T >, void * > dispatch=nullptr)
template<class F , class... Variants>
auto visit (F &&f, Variants &&... variants)
Variables
template<class T >
constexpr bool is_variant_wrapper = std::is_base_of_v<VarWrapBase, std::decay_t<T>>
Typedef Documentation
GenericVector
template<class T > using dismec::types::GenericVector = typedef GenericMatrix<DenseVector < T>, SparseVector <T> >
Definition at line 26 of file matrix_types.h.
Function Documentation
unpack_variant_wrapper() [1/2]
template<class T > decltype(auto) dismec::types::unpack_variant_wrapper (T && source, std::enable_if_t< is_variant_wrapper< T >, void * > dispatch = nullptr)
Definition at line 89 of file eigen_generic.h.
unpack_variant_wrapper() [2/2]
template<class T > decltype(auto) dismec::types::unpack_variant_wrapper (T && source, std::enable_if_t<!is_variant_wrapper< T >, void * > dispatch = nullptr)
Definition at line 84 of file eigen_generic.h.
Referenced by visit().
visit()
template<class F , class... Variants> auto dismec::types::visit (F && f, Variants &&... variants)
Definition at line 95 of file eigen_generic.h.
References unpack_variant_wrapper().
Referenced by dismec::HyperParameters::apply(), dismec::augment_features_with_bias(), dismec::types::EigenVariantWrapper< Types >::cols(), dismec::init::create_ova_primal_initializer(), dismec::HyperParameterBase::declare_sub_object(), dismec::objective::GenericLinearClassifier::diag_preconditioner_unchecked(), dismec::prediction::PredictionBase::do_prediction(), dismec::HyperParameterBase::get_hyper_parameter(), dismec::init::MeanOfFeaturesInitializer::get_initial_weight(), dismec::get_mean_feature(), dismec::objective::GenericLinearClassifier::gradient_and_pre_conditioner_unchecked(), dismec::objective::GenericLinearClassifier::gradient_at_zero_unchecked(), dismec::objective::GenericLinearClassifier::gradient_unchecked(), dismec::objective::GenericLinearClassifier::hessian_times_direction_unchecked(), dismec::DiSMECTraining::make_objective(), dismec::normalize_instances(), dismec::model::DenseModel::predict_scores_unchecked(), dismec::model::SparseModel::predict_scores_unchecked(), dismec::objective::LinearClassifierBase::project_linear_to_line(), dismec::types::EigenVariantWrapper< Types >::rows(), dismec::model::DenseModel::set_weights_for_label_unchecked(), dismec::model::SparseModel::set_weights_for_label_unchecked(), dismec::types::EigenVariantWrapper< Types >::size(), dismec::sort_features_by_frequency(), dismec::transform_features(), and dismec::objective::LinearClassifierBase::x_times_w().
Variable Documentation
is_variant_wrapper
template<class T > constexpr bool dismec::types::is_variant_wrapper = std::is_base_of_v<VarWrapBase, std::decay_t<T>> constexpr
Definition at line 80 of file eigen_generic.h.