DiSMEC++: dismec::postproc Namespace Reference
dismec::postproc Namespace Reference
Classes
class CombinePostProcessor
class CombinedFactory
class GenericPostProcFactory
class ReorderPostProc
class Sparsify
struct IdentityPostProc
class CullingPostProcessor
class PostProcessor
class PostProcessFactory
Typedefs
using FactoryPtr = std::shared_ptr< PostProcessFactory >
Functions
FactoryPtr create_identity ()
FactoryPtr create_culling (real_t eps)
FactoryPtr create_sparsify (real_t tolerance)
FactoryPtr create_combined (std::vector< FactoryPtr > processor)
FactoryPtr create_reordering (Eigen::PermutationMatrix< Eigen::Dynamic, Eigen::Dynamic, int > ordering)
Typedef Documentation
FactoryPtr
using dismec::postproc::FactoryPtr = typedef std::shared_ptr<PostProcessFactory>
Definition at line 16 of file postproc.h.
Function Documentation
create_combined()
FactoryPtr dismec::postproc::create_combined (std::vector< FactoryPtr > processor)
create_culling()
std::shared_ptr< PostProcessFactory > dismec::postproc::create_culling (real_t eps)
Definition at line 54 of file postproc.cpp.
Referenced by register_training(), and TrainingProgram::run().
create_identity()
std::shared_ptr< PostProcessFactory > dismec::postproc::create_identity ()
Definition at line 50 of file postproc.cpp.
Referenced by dismec::create_cascade_training(), and dismec::create_dismec_training().
create_reordering()
std::shared_ptr< dismec::postproc::PostProcessFactory > dismec::postproc::create_reordering (Eigen::PermutationMatrix< Eigen::Dynamic, Eigen::Dynamic, int > ordering)
Definition at line 25 of file reorder.cpp.
create_sparsify()
std::shared_ptr< dismec::postproc::PostProcessFactory > dismec::postproc::create_sparsify (real_t tolerance)
Definition at line 167 of file sparsify.cpp.