DiSMEC++: dismec::objective Namespace Reference
dismec::objective Namespace Reference
Classes
class DenseAndSparseLinearBase
Base class for implementationa of an objective that combines dense features and sparse features.
struct DenseAndSparseMargin
class GenericLinearClassifier
This is a non-templated, runtime-polymorphic generic implementation of the linear classifier objective.
struct GenericMarginClassifier
A utility class template that, when instatiated with a MarginFunction, produces the corresponding linear classifier loss.
class LinearClassifierBase
Base class for objectives that use a linear classifier.
class LinearClassifierImpBase
Implementation helper for linear classifier derived classes.
struct SquaredHingePhi
struct HuberPhi
struct LogisticPhi
class Objective
Class that models an optimization objective.
class PointWiseRegularizer
Base class for pointwise regularization functions.
class Regularized_SquaredHingeSVC
struct SquaredNormConfig
struct HuberConfig
struct ElasticConfig
class SquaredNormRegularizer
This class implements a squared norm (L2) regularizer. Thus f(x) = 0.5 |x|^2.
class HuberRegularizer
This class implements a huber regularizer.
class ElasticNetRegularizer
Functions
std::unique_ptr< DenseAndSparseLinearBase > make_sp_dense_squared_hinge (std::shared_ptr< const GenericFeatureMatrix > dense_features, real_t dense_reg_strength, std::shared_ptr< const GenericFeatureMatrix > sparse_features, real_t sparse_reg_strength)
std::unique_ptr< GenericLinearClassifier > make_squared_hinge (std::shared_ptr< const GenericFeatureMatrix > X, std::unique_ptr< Objective > regularizer)
std::unique_ptr< GenericLinearClassifier > make_logistic_loss (std::shared_ptr< const GenericFeatureMatrix > X, std::unique_ptr< Objective > regularizer)
std::unique_ptr< GenericLinearClassifier > make_huber_hinge (std::shared_ptr< const GenericFeatureMatrix > X, std::unique_ptr< Objective > regularizer, real_t epsilon)
std::unique_ptr< Objective > make_regularizer (const SquaredNormConfig &config)
std::unique_ptr< Objective > make_regularizer (const HuberConfig &config)
std::unique_ptr< Objective > make_regularizer (const ElasticConfig &config)
Detailed Description
Regularizers are implementations of Objective that depend only on the weight vector, but make no reference to external data. From the Objective interface, this is not visible, since the data is not part of the public interface.
Function Documentation
make_huber_hinge()
std::unique_ptr< GenericLinearClassifier > dismec::objective::make_huber_hinge (std::shared_ptr< const GenericFeatureMatrix > X, std::unique_ptr< Objective > regularizer, real_t epsilon)
Definition at line 185 of file generic_linear.cpp.
Referenced by dismec::make_loss().
make_logistic_loss()
std::unique_ptr< GenericLinearClassifier > dismec::objective::make_logistic_loss (std::shared_ptr< const GenericFeatureMatrix > X, std::unique_ptr< Objective > regularizer)
Definition at line 180 of file generic_linear.cpp.
Referenced by dismec::make_loss().
make_regularizer() [1/3]
std::unique_ptr< Objective > dismec::objective::make_regularizer (const ElasticConfig & config)
Definition at line 134 of file regularizers_imp.cpp.
References dismec::objective::ElasticConfig::Epsilon, dismec::objective::ElasticConfig::IgnoreBias, dismec::objective::ElasticConfig::Interpolation, and dismec::objective::ElasticConfig::Strength.
make_regularizer() [2/3]
std::unique_ptr< Objective > dismec::objective::make_regularizer (const HuberConfig & config)
Definition at line 130 of file regularizers_imp.cpp.
References dismec::objective::HuberConfig::Epsilon, dismec::objective::HuberConfig::IgnoreBias, and dismec::objective::HuberConfig::Strength.
make_regularizer() [3/3]
std::unique_ptr< Objective > dismec::objective::make_regularizer (const SquaredNormConfig & config)
Definition at line 126 of file regularizers_imp.cpp.
References dismec::objective::SquaredNormConfig::IgnoreBias, and dismec::objective::SquaredNormConfig::Strength.
Referenced by dismec::init::create_ova_primal_initializer(), and dismec::DiSMECTraining::make_objective().
make_sp_dense_squared_hinge()
std::unique_ptr< DenseAndSparseLinearBase > dismec::objective::make_sp_dense_squared_hinge (std::shared_ptr< const GenericFeatureMatrix > dense_features, real_t dense_reg_strength, std::shared_ptr< const GenericFeatureMatrix > sparse_features, real_t sparse_reg_strength)
Definition at line 247 of file dense_and_sparse.cpp.
Referenced by dismec::CascadeTraining::make_objective().
make_squared_hinge()
std::unique_ptr< GenericLinearClassifier > dismec::objective::make_squared_hinge (std::shared_ptr< const GenericFeatureMatrix > X, std::unique_ptr< Objective > regularizer)
Definition at line 175 of file generic_linear.cpp.
Referenced by dismec::make_loss(), and TEST_CASE().