DiSMEC++: src/predict.cpp File Reference
predict.cpp File Reference
#include "prediction/metrics.h"
#include "parallel/runner.h"
#include "prediction/prediction.h"
#include "prediction/evaluate.h"
#include "model/model.h"
#include "data/data.h"
#include "data/transform.h"
#include "io/model-io.h"
#include "io/prediction.h"
#include "io/xmc.h"
#include "CLI/CLI.hpp"
#include "app.h"
#include "spdlog/spdlog.h"
#include "nlohmann/json.hpp"
Functions
prediction::MacroMetricReporter * add_macro_metrics (prediction::EvaluateMetrics &metrics, int k)
void setup_metrics (prediction::EvaluateMetrics &metrics, int top_k)
int main (int argc, const char **argv)
Function Documentation
add_macro_metrics()
prediction::MacroMetricReporter* add_macro_metrics (prediction::EvaluateMetrics & metrics, int k)
Definition at line 24 of file predict.cpp.
References dismec::prediction::MacroMetricReporter::add_coverage(), dismec::prediction::MacroMetricReporter::MACRO, and dismec::prediction::MacroMetricReporter::MICRO.
Referenced by setup_metrics().
main()
int main (int argc, const char ** argv)
Definition at line 84 of file predict.cpp.
References dismec::io::model::PartialModelLoader::DEFAULT, dismec::prediction::TopKPredictionTaskGenerator::FALSE_NEGATIVES, dismec::prediction::TopKPredictionTaskGenerator::FALSE_POSITIVES, dismec::DataProcessing::load(), dismec::io::model::PartialModelLoader::load_model(), dismec::io::model::PartialModelLoader::num_weight_files(), dismec::PREDICTION_METRICS_CHUNK_SIZE, dismec::PREDICTION_RUN_CHUNK_SIZE, dismec::parallel::ParallelRunner::run(), dismec::io::prediction::save_sparse_predictions(), dismec::parallel::ParallelRunner::set_chunk_size(), dismec::parallel::ParallelRunner::set_logger(), dismec::DataProcessing::setup_data_args(), setup_metrics(), dismec::opaque_int_type< Tag, T >::to_index(), dismec::prediction::TopKPredictionTaskGenerator::TRUE_NEGATIVES, dismec::prediction::TopKPredictionTaskGenerator::TRUE_POSITIVES, and dismec::io::model::PartialModelLoader::validate().
setup_metrics()
void setup_metrics (prediction::EvaluateMetrics & metrics, int top_k)
Definition at line 59 of file predict.cpp.
References add_macro_metrics().
Referenced by main().