DiSMEC++: src/python/py_data.cpp File Reference
py_data.cpp File Reference
#include "binding.h"
#include "data/data.h"
#include "io/xmc.h"
#include "io/slice.h"
Namespaces
anonymous_namespace{py_data.cpp}
Macros
#define PY_PROPERTY(function) def_property(#function, [](const DatasetBase& pds){ return pds.function(); } , nullptr)
Typedefs
using PyDataSet = std::shared_ptr< DatasetBase >
Functions
auto anonymous_namespace{py_data.cpp}::num_positives (const DatasetBase &ds, long label)
auto anonymous_namespace{py_data.cpp}::num_negatives (const DatasetBase &ds, long label)
auto anonymous_namespace{py_data.cpp}::get_labels (const DatasetBase &ds, long id)
auto anonymous_namespace{py_data.cpp}::get_features (const DatasetBase &ds)
auto anonymous_namespace{py_data.cpp}::set_features_sparse (DatasetBase &ds, SparseFeatures features)
auto anonymous_namespace{py_data.cpp}::set_features_dense (DatasetBase &ds, DenseFeatures features)
PyDataSet anonymous_namespace{py_data.cpp}::load_xmc (const std::filesystem::path &source_file, bool one_based_indexing)
void anonymous_namespace{py_data.cpp}::save_xmc (const std::filesystem::path &target_file, const DatasetBase &ds, int precision)
PyDataSet anonymous_namespace{py_data.cpp}::load_slice (const std::filesystem::path &features_file, const std::filesystem::path &labels_file)
void register_dataset (pybind11::module_ &m)
Macro Definition Documentation
PY_PROPERTY
#define PY_PROPERTY (function) def_property(#function, [](const DatasetBase& pds){ return pds.function(); } , nullptr)
Definition at line 15 of file py_data.cpp.
Typedef Documentation
PyDataSet
using PyDataSet = std::shared_ptr<DatasetBase>
Definition at line 13 of file py_data.cpp.
Function Documentation
register_dataset()
void register_dataset (pybind11::module_ & m)
Definition at line 55 of file py_data.cpp.
References anonymous_namespace{py_data.cpp}::get_features(), anonymous_namespace{py_data.cpp}::get_labels(), anonymous_namespace{py_data.cpp}::load_slice(), anonymous_namespace{py_data.cpp}::load_xmc(), anonymous_namespace{py_data.cpp}::num_negatives(), anonymous_namespace{py_data.cpp}::num_positives(), dismec::confusion_matrix_detail::positives(), PY_PROPERTY, anonymous_namespace{py_data.cpp}::save_xmc(), anonymous_namespace{py_data.cpp}::set_features_dense(), and anonymous_namespace{py_data.cpp}::set_features_sparse().
Referenced by PYBIND11_MODULE().