DiSMEC++: src/python/py_train.cpp File Reference
py_train.cpp File Reference
#include "binding.h"
#include "data/data.h"
#include "training/weighting.h"
#include "training/training.h"
#include "training/initializer.h"
#include "training/postproc.h"
#include "parallel/runner.h"
#include "objective/regularizers.h"
#include "spdlog/fmt/fmt.h"
Namespaces
anonymous_namespace{py_train.cpp}
Typedefs
using PyWeighting = std::shared_ptr< WeightingScheme >
Functions
void register_regularizers (pybind11::module_ &root)
auto anonymous_namespace{py_train.cpp}::get_positive_weight (const WeightingScheme &pds, long label)
auto anonymous_namespace{py_train.cpp}::get_negative_weight (const WeightingScheme &pds, long label)
PyWeighting anonymous_namespace{py_train.cpp}::make_constant (double pos, double neg)
PyWeighting anonymous_namespace{py_train.cpp}::make_propensity (const DatasetBase &data, double a, double b)
PyWeighting anonymous_namespace{py_train.cpp}::make_custom (DenseRealVector pos, DenseRealVector neg)
void register_weighting (pybind11::module_ &m)
void register_init (pybind11::module_ &root)
void register_training (pybind11::module_ &m)
Typedef Documentation
PyWeighting
using PyWeighting = std::shared_ptr<WeightingScheme>
Definition at line 21 of file py_train.cpp.
Function Documentation
register_init()
void register_init (pybind11::module_ & root)
Definition at line 96 of file py_train.cpp.
References dismec::init::create_constant_initializer(), dismec::init::create_feature_mean_initializer(), dismec::init::create_multi_pos_mean_strategy(), dismec::init::create_ova_primal_initializer(), and dismec::init::create_zero_initializer().
Referenced by register_training().
register_regularizers()
void register_regularizers (pybind11::module_ & root)
Definition at line 23 of file py_train.cpp.
References dismec::objective::HuberConfig::Epsilon, dismec::objective::ElasticConfig::Epsilon, dismec::objective::SquaredNormConfig::IgnoreBias, dismec::objective::HuberConfig::IgnoreBias, dismec::objective::ElasticConfig::IgnoreBias, dismec::objective::ElasticConfig::Interpolation, dismec::objective::SquaredNormConfig::Strength, dismec::objective::HuberConfig::Strength, and dismec::objective::ElasticConfig::Strength.
Referenced by register_training().
register_training()
void register_training (pybind11::module_ & m)
Definition at line 123 of file py_train.cpp.
References dismec::postproc::create_culling(), dismec::create_dismec_training(), dismec::HINGE, dismec::HUBER_HINGE, dismec::LOGISTIC, dismec::DismecTrainingConfig::Loss, register_init(), register_regularizers(), register_weighting(), dismec::DismecTrainingConfig::Regularizer, dismec::run_training(), dismec::parallel::ParallelRunner::set_logger(), dismec::DismecTrainingConfig::Sparse, dismec::SQUARED_HINGE, dismec::TrainingResult::TotalLoss, and dismec::DismecTrainingConfig::Weighting.
Referenced by PYBIND11_MODULE().
register_weighting()
void register_weighting (pybind11::module_ & m)
Definition at line 82 of file py_train.cpp.
References anonymous_namespace{py_train.cpp}::get_negative_weight(), anonymous_namespace{py_train.cpp}::get_positive_weight(), anonymous_namespace{py_train.cpp}::make_constant(), anonymous_namespace{py_train.cpp}::make_custom(), and anonymous_namespace{py_train.cpp}::make_propensity().
Referenced by register_training().