DiSMEC++: src/pybind.cpp File Reference
pybind.cpp File Reference
#include <utility>
#include "python/binding.h"
#include "pybind11/pybind11.h"
#include "pybind11/eigen.h"
#include "pybind11/stl.h"
#include "data/data.h"
#include "model/model.h"
#include "io/xmc.h"
#include "io/model-io.h"
#include "io/prediction.h"
#include "training/weighting.h"
#include "training/training.h"
#include "training/initializer.h"
#include "parallel/runner.h"
Macros
#define PY_PROPERTY(type, function) def_property(#function, [](const type& pds){ return pds->function(); } , nullptr)
Typedefs
using PyTrainSpec = PyWrapper< TrainingSpec >
using PySaver = PyWrapper< io::PartialModelSaver >
Functions
void register_dataset (pybind11::module_ &m)
void register_training (pybind11::module_ &m)
PYBIND11_MODULE (pydismec, m)
Macro Definition Documentation
PY_PROPERTY
#define PY_PROPERTY (type, function) def_property(#function, [](const type& pds){ return pds->function(); } , nullptr)
Definition at line 31 of file pybind.cpp.
Typedef Documentation
PySaver
using PySaver = PyWrapper<io::PartialModelSaver>
Definition at line 29 of file pybind.cpp.
PyTrainSpec
using PyTrainSpec = PyWrapper<TrainingSpec>
Definition at line 28 of file pybind.cpp.
Function Documentation
PYBIND11_MODULE()
PYBIND11_MODULE (pydismec , m)
Definition at line 37 of file pybind.cpp.
References PyWrapper< T >::access(), dismec::io::model::WeightFileEntry::Count, dismec::io::model::SaveOption::Culling, dismec::io::model::WeightFileEntry::FileName, dismec::io::model::WeightFileEntry::First, dismec::io::model::SaveOption::Format, dismec::io::model::WeightFileEntry::Format, dismec::io::model::load_model(), dismec::io::model::parse_weights_format(), dismec::io::model::SaveOption::Precision, dismec::confusion_matrix_detail::precision(), PyWrapper< T >::ptr(), PY_PROPERTY, dismec::io::prediction::read_sparse_prediction(), register_dataset(), register_training(), dismec::opaque_int_type< Tag, T >::to_index(), and dismec::io::model::to_string().
register_dataset()
void register_dataset (pybind11::module_ & m)
Definition at line 55 of file py_data.cpp.
References anonymous_namespace{py_data.cpp}::get_features(), anonymous_namespace{py_data.cpp}::get_labels(), anonymous_namespace{py_data.cpp}::load_slice(), anonymous_namespace{py_data.cpp}::load_xmc(), anonymous_namespace{py_data.cpp}::num_negatives(), anonymous_namespace{py_data.cpp}::num_positives(), dismec::confusion_matrix_detail::positives(), PY_PROPERTY, anonymous_namespace{py_data.cpp}::save_xmc(), anonymous_namespace{py_data.cpp}::set_features_dense(), and anonymous_namespace{py_data.cpp}::set_features_sparse().
Referenced by PYBIND11_MODULE().
register_training()
void register_training (pybind11::module_ & m)
Definition at line 123 of file py_train.cpp.
References dismec::postproc::create_culling(), dismec::create_dismec_training(), dismec::HINGE, dismec::HUBER_HINGE, dismec::LOGISTIC, dismec::DismecTrainingConfig::Loss, register_init(), register_regularizers(), register_weighting(), dismec::DismecTrainingConfig::Regularizer, dismec::run_training(), dismec::parallel::ParallelRunner::set_logger(), dismec::DismecTrainingConfig::Sparse, dismec::SQUARED_HINGE, dismec::TrainingResult::TotalLoss, and dismec::DismecTrainingConfig::Weighting.
Referenced by PYBIND11_MODULE().