DiSMEC++: src/objective/regularizers_imp.cpp File Reference
regularizers_imp.cpp File Reference
#include "regularizers_imp.h"
#include "regularizers.h"
#include "utils/hash_vector.h"
#include "utils/conversion.h"
#include "doctest.h"
#include "spdlog/spdlog.h"
Namespaces
anonymous_namespace{regularizers_imp.cpp}
Functions
DenseRealVector anonymous_namespace{regularizers_imp.cpp}::make_vec (std::initializer_list< real_t > values)
void anonymous_namespace{regularizers_imp.cpp}::verify_line_search (objective::Objective &reg)
void anonymous_namespace{regularizers_imp.cpp}::verify_bias (objective::Objective &full, objective::Objective &no_bias)
TEST_CASE ("l2-reg")
TEST_CASE ("l2 line-search")
TEST_CASE ("l2 bias")
TEST_CASE ("huber-reg")
TEST_CASE ("huber line-search")
TEST_CASE ("huber bias")
TEST_CASE ("elastic-net")
TEST_CASE ("elastic line-search")
TEST_CASE ("elastic bias")
Function Documentation
TEST_CASE() [1/9]
TEST_CASE ("elastic bias")
Definition at line 364 of file regularizers_imp.cpp.
References anonymous_namespace{regularizers_imp.cpp}::verify_bias().
TEST_CASE() [2/9]
TEST_CASE ("elastic line-search")
Definition at line 348 of file regularizers_imp.cpp.
References anonymous_namespace{regularizers_imp.cpp}::verify_line_search().
TEST_CASE() [3/9]
TEST_CASE ("elastic-net")
Definition at line 297 of file regularizers_imp.cpp.
References dismec::objective::Objective::gradient(), and dismec::objective::Objective::value().
TEST_CASE() [4/9]
TEST_CASE ("huber bias")
Definition at line 291 of file regularizers_imp.cpp.
References anonymous_namespace{regularizers_imp.cpp}::verify_bias().
TEST_CASE() [5/9]
TEST_CASE ("huber line-search")
Definition at line 275 of file regularizers_imp.cpp.
References anonymous_namespace{regularizers_imp.cpp}::verify_line_search().
TEST_CASE() [6/9]
TEST_CASE ("huber-reg")
Definition at line 256 of file regularizers_imp.cpp.
References dismec::objective::Objective::gradient(), dismec::objective::Objective::gradient_at_zero(), and dismec::objective::Objective::value().
TEST_CASE() [7/9]
TEST_CASE ("l2 bias")
Definition at line 250 of file regularizers_imp.cpp.
References anonymous_namespace{regularizers_imp.cpp}::verify_bias().
TEST_CASE() [8/9]
TEST_CASE ("l2 line-search")
Definition at line 235 of file regularizers_imp.cpp.
References anonymous_namespace{regularizers_imp.cpp}::verify_line_search().
TEST_CASE() [9/9]
TEST_CASE ("l2-reg")
Definition at line 203 of file regularizers_imp.cpp.
References dismec::objective::Objective::diag_preconditioner(), dismec::objective::Objective::gradient(), dismec::objective::Objective::gradient_at_zero(), dismec::objective::Objective::hessian_times_direction(), anonymous_namespace{regularizers_imp.cpp}::make_vec(), and dismec::objective::Objective::value().