DiSMEC++: src/parallel/runner.cpp File Reference
runner.cpp File Reference
#include <algorithm>
#include <thread>
#include <atomic>
#include "config.h"
#include "parallel/runner.h"
#include "parallel/task.h"
#include "parallel/numa.h"
#include "utils/conversion.h"
#include "doctest.h"
Classes
struct anonymous_namespace{runner.cpp}::DummyTask
Namespaces
anonymous_namespace{runner.cpp}
Functions
template<class T >
auto anonymous_namespace{runner.cpp}::to_ms (T &&arg)
TEST_CASE ("run parallel")
TEST_CASE ("run chunked parallel with start pos")
TEST_CASE ("run parallel with timeout")
Function Documentation
TEST_CASE() [1/3]
TEST_CASE ("run chunked parallel with start pos")
Definition at line 204 of file runner.cpp.
References dismec::parallel::ParallelRunner::run(), and dismec::ssize().
TEST_CASE() [2/3]
TEST_CASE ("run parallel with timeout")
Definition at line 220 of file runner.cpp.
References dismec::parallel::ParallelRunner::set_time_limit(), and dismec::ssize().
TEST_CASE() [3/3]
TEST_CASE ("run parallel")
Definition at line 192 of file runner.cpp.
References dismec::parallel::ParallelRunner::run(), and dismec::ssize().