DiSMEC++: anonymous_namespace{sparse.cpp}::PredictVisitor Struct Reference
anonymous_namespace{sparse.cpp}::PredictVisitor Struct Reference
Public Member Functions
PredictVisitor (const Eigen::Ref< PredictionMatrix > &target, const std::vector< SparseRealVector > *weights)
void operator() (const GenericInMatrix::DenseColMajorRef &instances)
void operator() (const GenericInMatrix::DenseRowMajorRef &instances)
void operator() (const GenericInMatrix::SparseColMajorRef &instances)
void operator() (const GenericInMatrix::SparseRowMajorRef &instances)
Public Attributes
Eigen::Ref< PredictionMatrix > Target
const std::vector< SparseRealVector > * Weights
Detailed Description
Definition at line 44 of file sparse.cpp.
Constructor & Destructor Documentation
PredictVisitor()
anonymous_namespace{sparse.cpp}::PredictVisitor::PredictVisitor (const Eigen::Ref< PredictionMatrix > & target, const std::vector< SparseRealVector > * weights) inline
Definition at line 45 of file sparse.cpp.
Member Function Documentation
operator()() [1/4]
void anonymous_namespace{sparse.cpp}::PredictVisitor::operator() (const GenericInMatrix::DenseColMajorRef & instances) inline
Definition at line 49 of file sparse.cpp.
References dismec::ssize().
operator()() [2/4]
void anonymous_namespace{sparse.cpp}::PredictVisitor::operator() (const GenericInMatrix::DenseRowMajorRef & instances) inline
Definition at line 55 of file sparse.cpp.
References dismec::ssize().
operator()() [3/4]
void anonymous_namespace{sparse.cpp}::PredictVisitor::operator() (const GenericInMatrix::SparseColMajorRef & instances) inline
Definition at line 61 of file sparse.cpp.
References dismec::ssize().
operator()() [4/4]
void anonymous_namespace{sparse.cpp}::PredictVisitor::operator() (const GenericInMatrix::SparseRowMajorRef & instances) inline
Definition at line 67 of file sparse.cpp.
References dismec::ssize().
Member Data Documentation
Target
Eigen::Ref<PredictionMatrix> anonymous_namespace{sparse.cpp}::PredictVisitor::Target
Definition at line 74 of file sparse.cpp.
Weights
const std::vector<SparseRealVector>* anonymous_namespace{sparse.cpp}::PredictVisitor::Weights
Definition at line 75 of file sparse.cpp.
The documentation for this struct was generated from the following file:
src/model/sparse.cpp