DiSMEC++: dismec::objective::HuberPhi Struct Reference
dismec::objective::HuberPhi Struct Reference
#include <margin_losses.h>
Public Member Functions
real_t value (real_t margin) const
real_t grad (real_t margin) const
real_t quad (real_t margin) const
Public Attributes
real_t Epsilon = 1
Detailed Description
Definition at line 32 of file margin_losses.h.
Member Function Documentation
grad()
real_t dismec::objective::HuberPhi::grad (real_t margin) const inline
Definition at line 39 of file margin_losses.h.
References Epsilon, and value().
quad()
real_t dismec::objective::HuberPhi::quad (real_t margin) const inline
Definition at line 50 of file margin_losses.h.
References Epsilon, and value().
value()
real_t dismec::objective::HuberPhi::value (real_t margin) const inline
Definition at line 33 of file margin_losses.h.
References Epsilon.
Referenced by grad(), and quad().
Member Data Documentation
Epsilon
real_t dismec::objective::HuberPhi::Epsilon = 1
Definition at line 57 of file margin_losses.h.
Referenced by grad(), quad(), and value().
The documentation for this struct was generated from the following file:
src/objective/margin_losses.h