DiSMEC++: dismec::objective::SquaredHingePhi Struct Reference
dismec::objective::SquaredHingePhi Struct Reference
#include <margin_losses.h>
Public Member Functions
real_t value (real_t margin) const
real_t grad (real_t margin) const
real_t quad (real_t margin) const
Detailed Description
Definition at line 15 of file margin_losses.h.
Member Function Documentation
grad()
real_t dismec::objective::SquaredHingePhi::grad (real_t margin) const inline
Definition at line 21 of file margin_losses.h.
References value().
quad()
real_t dismec::objective::SquaredHingePhi::quad (real_t margin) const inline
Definition at line 26 of file margin_losses.h.
References value().
value()
real_t dismec::objective::SquaredHingePhi::value (real_t margin) const inline
Definition at line 16 of file margin_losses.h.
Referenced by grad(), and quad().
The documentation for this struct was generated from the following file:
src/objective/margin_losses.h