DiSMEC++: src/tools/tfidf.cpp File Reference
tfidf.cpp File Reference
#include "io/xmc.h"
#include "data/data.h"
#include "data/transform.h"
#include "CLI/CLI.hpp"
#include "spdlog/spdlog.h"
#include "spdlog/stopwatch.h"
Functions
void apply_tfidf (SparseFeatures &features, const DenseRealVector &idf)
int main (int argc, const char **argv)
Function Documentation
apply_tfidf()
void apply_tfidf (SparseFeatures & features, const DenseRealVector & idf)
Definition at line 14 of file tfidf.cpp.
References dismec::normalize_instances().
Referenced by main().
main()
int main (int argc, const char ** argv)
Definition at line 24 of file tfidf.cpp.
References apply_tfidf(), dismec::count_features(), dismec::io::ONE_BASED, dismec::io::read_xmc_dataset(), dismec::io::save_xmc_dataset(), and dismec::io::ZERO_BASED.